# Generated by Django 3.1.6 on 2021-03-16 03:49

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='context',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True, verbose_name='Context'),
        ),
    ]
